name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: VPS_HOST

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Install Composer dependencies locally
      run: composer install --prefer-dist --no-ansi --no-interaction --no-scripts --no-dev --optimize-autoloader

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        script: |
          cd /var/www/html/AviaFly-Backend
          sudo chown -R marco:marco /var/www/html
          git pull origin main
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan optimize
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo chown -R www-data:www-data /var/www/html
          sudo systemctl restart apache2
