name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: VPS_HOST

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    # Instalar PHP 8.2
    - name: Set up PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer

    # Instalar dependencias de Composer
    - name: Install dependencies
      run: composer install --prefer-dist --no-ansi --no-interaction --no-scripts --no-dev --optimize-autoloader

    # Desplegar vía SSH
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        script: |
          cd /var/www/html/AviaFly-Backend
          sudo chown -R ubuntu:ubuntu /var/www/html
          git pull origin main
          composer install --no-dev --optimize-autoloader
          sudo php artisan optimize
          sudo php artisan cache:clear
          sudo chown -R www-data:www-data /var/www/html
          sudo systemctl restart apache2
